# Generated by Django 2.2.7 on 2020-01-15 09:20

import app.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('kurum', models.CharField(max_length=100, null=True, verbose_name='Kurum')),
                ('kurum_adres', models.CharField(max_length=200, null=True, verbose_name='Kurum adresi')),
                ('kurum_telefon', models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Telefon numarası şu şeklillerden biri gibi olmalı: '+9999999999' veya '9999999999' veya '999 9999999' veya '999 999 9999' veya '999 999 99 99'.", regex='^\\+?[1-9][0-9]{2} ?[0-9]{3} ?[0-9]{2} ?[0-9]{2}$')], verbose_name='Kurum telefonu')),
                ('kurum_web_adres', models.URLField(null=True, verbose_name='Kurum web adresi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', app.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='il',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ilan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=40, null=True, verbose_name='ilan adı')),
                ('adet', models.IntegerField(default=1, null=True, verbose_name='Adet')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('yayinda', models.BooleanField(default=True, verbose_name='Yayında')),
                ('olusturma_tarihi', models.DateField(auto_now=True)),
                ('silme_tarihi', models.DateField(blank=True, null=True)),
                ('kurum', models.CharField(blank=True, max_length=200, null=True)),
                ('kucuk_resim', models.ImageField(blank=True, editable=False, null=True, upload_to='silinenilanlar')),
            ],
        ),
        migrations.CreateModel(
            name='ilce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=35)),
                ('ill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.il')),
            ],
        ),
        migrations.CreateModel(
            name='Resim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(null=True, upload_to='', verbose_name='Resim')),
                ('kucukResim', models.ImageField(blank=True, editable=False, null=True, upload_to='thumbs')),
                ('ilan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ilan')),
            ],
            options={
                'ordering': ['ilan'],
            },
        ),
        migrations.CreateModel(
            name='Mesajlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yon', models.CharField(choices=[('gelen', 'gelen'), ('giden', 'giden')], default='gelen', max_length=5)),
                ('mesaj_metni', models.TextField(default='')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('okundu', models.BooleanField(default=False)),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ilan')),
            ],
        ),
        migrations.CreateModel(
            name='mahalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=50)),
                ('ilcee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ilce')),
            ],
        ),
        migrations.CreateModel(
            name='KayitBekleyenler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Kurum e-posta adresi')),
                ('kurum', models.CharField(max_length=100, null=True, verbose_name='Kurum adı')),
                ('kurum_adres', models.CharField(max_length=200, null=True, verbose_name='Kurum adresi')),
                ('kurum_telefon', models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Telefon numarası şu şeklillerden biri gibi olmalı: '+9999999999' veya '9999999999' veya '999 9999999' veya '999 999 9999' veya '999 999 99 99'. ", regex='^\\+?[1-9][0-9]{2} ?[0-9]{3} ?[0-9]{2} ?[0-9]{2}$')], verbose_name='Kurum telefonu')),
                ('kurum_web_adres', models.URLField(blank=True, null=True, verbose_name='Kurum web adresi')),
                ('kurum_il', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.il')),
                ('kurum_ilce', smart_selects.db_fields.ChainedForeignKey(chained_field='kurum_il', chained_model_field='ill', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ilce')),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=20, verbose_name='Kategori adı')),
                ('ust_kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Kategori')),
            ],
            options={
                'ordering': ('ust_kategori__ad', 'ad'),
            },
        ),
        migrations.AddField(
            model_name='ilan',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Kategori'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='sahip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='favoriler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ilan')),
                ('sahip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='kurum_il',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.il'),
        ),
        migrations.AddField(
            model_name='user',
            name='kurum_ilce',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='kurum_il', chained_model_field='ill', null=True, on_delete=django.db.models.deletion.CASCADE, sort=False, to='app.ilce'),
        ),
        migrations.AddField(
            model_name='user',
            name='kurum_mahalle',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='kurum_ilce', chained_model_field='ilcee', null=True, on_delete=django.db.models.deletion.CASCADE, sort=False, to='app.mahalle'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
