# Generated by Django 2.2.7 on 2020-01-15 13:01

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kayitbekleyenler',
            name='kurum_mahalle',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='kurum_ilce', chained_model_field='ilcee', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mahalle'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='kurum_mahalle',
        ),
        migrations.AddField(
            model_name='user',
            name='kurum_mahalle',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='kurum_ilce', chained_model_field='ilcee', null=True, to='app.mahalle'),
        ),
    ]
