# Generated by Django 2.2.7 on 2019-12-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Mesajlar',
            name='mesaj_metni',
            field=models.TextField(default=''),
        ),
    ]
