# Generated by Django 2.2.7 on 2020-01-16 10:08

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200116_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kurum_mahalle',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='kurum_ilce', chained_model_field='ilcee', null=True, on_delete=django.db.models.deletion.CASCADE, sort=False, to='app.mahalle'),
        ),
    ]
