# Generated by Django 2.2.7 on 2019-12-07 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191207_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kurum_adres',
            field=models.CharField(max_length=200, null=True, verbose_name='Kurum adresi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kurum_telefon',
            field=models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Telefon numarası şu şeklillerden biri gibi olmalı: '+9999999999' veya '9999999999' veya '999 9999999' veya '999 999 9999' veya '999 999 99 99'.", regex='^\\+?[1-9][0-9]{2} ?[0-9]{3} ?[0-9]{2} ?[0-9]{2}$')], verbose_name='Kurum telefonu'),
        ),
    ]
