# Generated by Django 2.2.7 on 2020-01-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200116_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='sikayet_nedenleri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sikayet', models.CharField(max_length=40)),
            ],
        ),
    ]
