# Generated by Django 2.2.7 on 2019-12-08 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191207_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategori',
            options={'ordering': ('ust_kategori__ad', 'ad')},
        ),
        migrations.CreateModel(
            name='favoriler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ilan')),
                ('sahip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
