# Generated by Django 2.2.7 on 2019-12-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191208_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='yayinda',
            field=models.BooleanField(default=True, verbose_name='Yayında'),
        ),
    ]
