# Generated by Django 2.2.7 on 2020-01-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200121_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='sikayet',
            name='aciklama',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
