# Generated by Django 2.2.7 on 2020-01-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sikayet_aciklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sikayet',
            name='aciklama',
            field=models.TextField(blank=True),
        ),
    ]
