# Generated by Django 2.2.7 on 2020-01-21 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200121_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesajlar',
            name='yon',
        ),
        migrations.AddField(
            model_name='mesajlar',
            name='gonderen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mesajlar',
            name='mesaj_metni',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sikayet',
            name='aciklama',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='sikayet',
            name='kim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sikayet',
            name='sikayet_nedeni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.sikayet_nedenleri', verbose_name='Şikayet Nedeni'),
        ),
    ]
