# Generated by Django 2.2.7 on 2019-12-17 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_geciciresimler'),
    ]

    operations = [
        migrations.CreateModel(
            name='geciciResim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(null=True, upload_to='', verbose_name='Resim')),
                ('ilan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ilan')),
            ],
        ),
        migrations.DeleteModel(
            name='geciciResimler',
        ),
    ]
