# Generated by Django 2.2.7 on 2019-12-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191217_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='geciciresim',
            name='kayitli',
            field=models.BooleanField(default=False),
        ),
    ]
