# Generated by Django 2.2.7 on 2020-01-28 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200122_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj_metni', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('gonderen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ilgili_ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ilan')),
            ],
        ),
        migrations.CreateModel(
            name='MesajHareketleri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gonderilen_id', models.IntegerField()),
                ('id_ilandir', models.BooleanField(default=True)),
                ('okundu', models.BooleanField(default=False)),
                ('mesaj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Mesaj')),
            ],
        ),
    ]
