# Generated by Django 2.2.7 on 2019-12-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_geciciresim_kayitli'),
    ]

    operations = [
        migrations.AddField(
            model_name='geciciresim',
            name='silinecek',
            field=models.BooleanField(default=False),
        ),
    ]
