# Generated by Django 2.2.7 on 2019-12-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_geciciresim_silinecek'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesajlar',
            name='okundu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='geciciresim',
            name='kayitli',
            field=models.BooleanField(default=True),
        ),
    ]
