# Generated by Django 2.2.7 on 2019-12-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20191217_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='tarih',
            field=models.DateField(auto_now=True),
        ),
    ]
