# Generated by Django 2.2.7 on 2020-01-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200129_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesaj',
            name='gonderen',
        ),
        migrations.RemoveField(
            model_name='mesajhareketleri',
            name='id_ilandir',
        ),
        migrations.AddField(
            model_name='mesajhareketleri',
            name='gonderen_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mesajhareketleri',
            name='gonderilen_id',
            field=models.IntegerField(null=True),
        ),
    ]
