# Generated by Django 2.2.7 on 2019-12-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_ilan_tarih'),
    ]

    operations = [
        migrations.AddField(
            model_name='resim',
            name='kayitli',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resim',
            name='silinecek',
            field=models.BooleanField(default=False),
        ),
    ]
