# Generated by Django 2.2.7 on 2020-01-29 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200129_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesaj',
            name='ilgili_ilan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ilan'),
        ),
    ]
