# Generated by Django 2.2.7 on 2019-12-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20191226_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='geciciresim',
            name='kucukResim',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
