# Generated by Django 2.2.7 on 2019-12-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_geciciresim_kucukresim'),
    ]

    operations = [
        migrations.AddField(
            model_name='resim',
            name='kucukResim',
            field=models.ImageField(editable=False, null=True, upload_to='thumbs'),
        ),
        migrations.AlterField(
            model_name='geciciresim',
            name='kucukResim',
            field=models.ImageField(editable=False, upload_to='thumbs'),
        ),
    ]
