# Generated by Django 2.2.7 on 2020-02-10 16:40

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200129_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolum_ad', models.CharField(max_length=50, verbose_name='Bölüm')),
            ],
            options={
                'ordering': ['bolum_ad'],
            },
        ),
        migrations.CreateModel(
            name='GorusKonulari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorus_konusu', models.CharField(max_length=30, verbose_name='Görüşün Konusu')),
            ],
        ),
        migrations.CreateModel(
            name='Sinif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinif', models.CharField(max_length=20, verbose_name='Sınıf')),
                ('sinifin_bolumu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Bolum')),
            ],
            options={
                'ordering': ['sinif'],
            },
        ),
        migrations.CreateModel(
            name='OgretmenBilgi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogretmen_ad', models.CharField(max_length=30, verbose_name='Öğretmen Adı')),
                ('ogretmen_soyad', models.CharField(max_length=30, verbose_name='Öğretmen Soyadı')),
                ('ogretmen_brans', models.CharField(max_length=30, verbose_name='Öğretmen Branşı')),
                ('ogretmen_sifre', models.CharField(max_length=30, verbose_name='Öğretmen Şifresi')),
                ('ogretmen_eposta', models.CharField(max_length=30, verbose_name='Öğretmen EPosta')),
                ('ogretmen_rehberlik_sinif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Sinif')),
            ],
            options={
                'ordering': ['ogretmen_ad'],
            },
        ),
        migrations.CreateModel(
            name='OgrenciBilgi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogrenci_tc', models.CharField(default='11112222333', max_length=11, verbose_name='TC Kimlik Numarası')),
                ('ogrenci_no', models.CharField(max_length=5, verbose_name='Öğrenci Numarası')),
                ('ogrenci_ad', models.CharField(max_length=30, null=True, verbose_name='Öğrenci Adı')),
                ('ogrenci_soyad', models.CharField(blank=True, max_length=30, null=True, verbose_name='Öğrenci Soyadı')),
                ('veli_isim', models.CharField(blank=True, max_length=30, null=True, verbose_name='Veli Ad Soyad ')),
                ('veli_telefon', models.CharField(blank=True, max_length=30, null=True, verbose_name='Veli Telefon')),
                ('veli_eposta', models.CharField(blank=True, max_length=30, null=True, verbose_name='Veli EPosta')),
                ('ogrenci_tel', models.CharField(blank=True, max_length=30, null=True, verbose_name='Öğrenci Telefon')),
                ('ogrenci_siniff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sinif')),
            ],
            options={
                'ordering': ['ogrenci_no'],
            },
        ),
        migrations.CreateModel(
            name='Gorusler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Görüş Tarihi')),
                ('olumlu', models.BooleanField()),
                ('gorus_metni', models.TextField(verbose_name='İçerik')),
                ('konu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.GorusKonulari')),
                ('ogrenci', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='sinif', chained_model_field='ogrenci_siniff', null=True, on_delete=django.db.models.deletion.CASCADE, sort=False, to='app.OgrenciBilgi')),
                ('ogretmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OgretmenBilgi')),
                ('sinif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sinif')),
            ],
        ),
    ]
