# Generated by Django 2.2.7 on 2019-12-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191227_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resim',
            name='kucukResim',
            field=models.ImageField(blank=True, editable=False, upload_to='thumbs'),
        ),
    ]
