# Generated by Django 2.2.7 on 2019-12-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20191227_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Silinen_ilanlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilan_ad', models.CharField(max_length=40, null=True, verbose_name='İlan adı')),
                ('kurum', models.CharField(max_length=100, null=True, verbose_name='Kurum')),
                ('kucukResim', models.ImageField(blank=True, editable=False, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='kayitbekleyenler',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Kurum e-posta adresi'),
        ),
        migrations.AlterField(
            model_name='kayitbekleyenler',
            name='kurum',
            field=models.CharField(max_length=100, null=True, verbose_name='Kurum adı'),
        ),
    ]
