# Generated by Django 2.2.7 on 2019-12-31 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20191231_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ilan',
            old_name='tarih',
            new_name='olusturma_tarihi',
        ),
        migrations.AddField(
            model_name='ilan',
            name='kucuk_resim',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='silinenilanlar'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='silme_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='sahip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
