# Generated by Django 2.2.7 on 2019-12-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20191231_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geciciresim',
            name='ilan',
        ),
        migrations.DeleteModel(
            name='Silinen_ilanlar',
        ),
        migrations.AddField(
            model_name='ilan',
            name='kurum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='geciciResim',
        ),
    ]
